---
name: Release
on:
  workflow_dispatch: {}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      ARTIFACTORY_TOKEN: '${{ secrets.ARTIFACTORY_TOKEN }}'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.8}

      - run: cp -f .ci.settings.xml $HOME/.m2/settings.xml
      - run: ./mvnw -B deploy

      - run: echo "PROJECT_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -DforceStdout -q)" >> $GITHUB_ENV
      - uses: mathieudutour/github-tag-action@v5.1
        id: version_tag
        with:
          custom_tag: '${{ env.PROJECT_VERSION }}'
          github_token: '${{ env.GITHUB_TOKEN }}'
      - uses: actions/create-release@v1
        with: {tag_name: '${{ steps.version_tag.outputs.new_tag }}'}
...